config/routes.rb
################################################################################
#   12.02.2022  Adopted from Rails 6 (zt_admin)
################################################################################
Rails.application.routes.draw do
  # mount_devise_token_auth_for 'Account', at: 'auth'
 
  app_scope = MULTILINGUAL ? "/:locale" : "/"
  scope app_scope, locale: /#{I18n.available_locales.join("|")}/ do

    # Session resources
    get    'sessions/new'                                # sessions_new_path
    post   'login',  to: 'sessions#create'               # login_path  - creates new session (login)
    get  'logout', to: 'sessions#destroy', as: :logout # logout_path - destroys    session (log out)
  # delete 'logout', to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)

    namespace :admin do
      root 'panel#index'                                 # admin_root_path
      resources :users
      resources :samples
      resources :accounts, only: [:index, :show]
      # Add new admin resources before this line
    end
  
    namespace :api do
      namespace :v1 do
        resources :samples
      end
    end
    root 'pages#home' 
    get :demo, to: 'pages#demo', path: 'demo'
    resources :people
  end

  if MULTILINGUAL
    # Root route is directed to default locale
    root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

    # All other routes without locales are directed to the same ones with locales
    #get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false
  
    # Active Storage paths are excluded from the redirection process
    get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(rails\/active_storage|#{I18n.available_locales.join("|")})\/).*/}, format: false
  end
end

Rails.application.routes.draw do
  resources :people
  get 'pages/demo'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
################################################################################
# Model:  User
#
# Purpose:  A Company User with access to Admin
#
# User attributes:
#   role              - enum { manager (0) | admin (1) | superadmin (2)}
#   last_name         - string:
#   first_name         - string:
#   email             - string,   not NULL, unique
#   password_digest   - password: string, not NULL
#   remember_token    - string
#   status            - enum { active (0) | archived (1) }
#
#   13.01.2022 ZT    Adopted for RoR 7 (from Rails 6 zt_admin)
################################################################################
class User < ApplicationRecord
  include Emailable

  enum role:   %w(manager admin superadmin)
  enum status: %w(active archived)

  # Error (nopt fixed):
  #   You tried to define an enum named "role" on the model "User", 
  #   but this will generate a instance method "manager?", 
  #   which is already defined by another enum. (ArgumentError)

  # enum role:   {manager: 1, admin: 1, superadmin: 2}
  # enum status: {active: 0, archived: 1}, default: :active

  validates :last_name, presence: true
  validates :first_name, presence: true

  has_secure_password  # validates presence of password & password_confirmation
  validates :password, length: {minimum: 8}

  # Returns an User full name
  def full_name
    "#{last_name} #{first_name}"
  end

  private

    # Returns a random token
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

    # Returns a random token.
    def User.new_token
      SecureRandom.urlsafe_base64
    end

    # Remembers a user in the database to apply him/her in persistent sessions
    def remember
      self.remember_token = User.new_token
      update_attribute(:remember_digest, User.digest(remember_token))
    end

    # Returns true if the given token matches the digest.
    def authenticated?(remember_token)
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
    authorize @users
  end

  def show
    authorize @user
  end

  def new
    @user = User.new
    authorize @user
  end

  def edit
    authorize @user
  end

  def create
    @user = User.new(user_params)
    authorize @user

    if @user.save
      flash[:success] = t('messages.created', model: @user.class.model_name.human)
      redirect_to [:admin, @user]
#     redirect_to polymorphic_url([:admin, @user], locale: params[:locale]), notice: t('messages.created', model: @user.class.model_name.human)
    else
      render :new
    end
  end

  def update
    authorize @user
    if @user.update(user_params)
      flash[:success] = t('messages.updated', model: @user.class.model_name.human)
      redirect_to [:admin, @user]
#     redirect_to polymorphic_url([:admin, @user], locale: params[:locale]), notice: t('messages.updated', model: @user.class.model_name.human)
    else
      render :edit
    end
  end

  def destroy
    authorize @user
    @user.destroy
    flash[:success] = t('messages.deleted', model: @user.class.model_name.human)
    redirect_to admin_users_path
  end

  private

    # Uses callbacks to share common setup or constraints between actions
    def set_user
      @user = User.find(params[:id])
    end

    # Only allows a trusted parameter 'white list' through
    def user_params
      params.require(:user).permit(:role, :last_name, :first_name, :email, :password_digest, :remember_digest, :status, :password, :password_confirmation)
    end
end

app/views/admin/users/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= simple_form_for([:admin, @user], html: {multipart: true}, url: (@user.id.nil? ? {action: 'create', locale: params[:locale]} : {action: 'update', locale: params[:locale]})) do |f| %>
      <div class="form-inputs">
        <%= f.error_notification message: t('messages.error_notification') %>
        <%= f.input :role, include_blank: false %>
        <%= f.input :last_name %>
        <%= f.input :first_name %>
        <%= f.input :email %>
        <%= f.input :password %>
        <%= f.input :password_confirmation %>
        <%= f.input :status %>
        <%#= render 'admin/shared/status_buttons', f: f   # Radio-buttons %>
      </div>
      </br>
      <div class="form_actions">
        <div class="row">
          <div class="col-sm-3">
            <%= f.submit t('actions.save'), class: 'btn btn-primary btn-sm' %>
          </div>
          <div class="col-sm-3">
            <% if @current_user.superadmin? %>
              <%= link_to t('actions.back'), admin_users_path, class: 'btn btn-info btn-sm' %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/edit.html.erb
<h1>
  <%= "#{t('actions.editing', model: @user.class.model_name.human)}" %>
</h1>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1><%= t User.model_name.human(count: 2) %></h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= User.human_attribute_name(:role) %></th>
      <th><%= User.human_attribute_name(:last_name) %></th>
      <th><%= User.human_attribute_name(:first_name) %></th>
      <th><%= User.human_attribute_name(:email) %></th>
      <th><%= t 'status.status' %></th>
      <th><%= t 'actions.actions' %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.role %></td>
        <td><%= user.last_name %></td>
        <td><%= user.first_name %></td>
        <td><%= user.email %></td>
        <td><%= status_mark user.status %></td>
        <td><%= render 'admin/shared/index_buttons', resource: user %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>
<div class="row">
  <div class="col-md-2">
    <%= link_to t('actions.create'), new_admin_user_path, class: 'btn btn-primary btn-sm' %>
  </div>
</div>

app/views/admin/users/new.html.erb
<h1>
  <%= "#{t('actions.new', model: @user.class.model_name.human)}" %>
</h1>
<%= render 'form' %>

app/views/admin/users/show.html.erb
<h1>
  <%= t User.model_name.human %>
</h1>
<table class="table table-striped">
  <tbody>
    <% @user.attributes.each do |key, value| %>
      <% if key == 'id' || key.include?('digest') || key == 'created_at' || key == 'updated_at' %>
        <!--/skip these attributes -->
      <% else %>
        <tr>
          <% if key == 'status' %>
            <td><%= t 'status.status' %></td>
            <td><%= status_mark @user.status %></td>
          <% else %>
            <td><%= t "activerecord.attributes.user.#{key}" %></td>
            <td><%= value %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<div class="form_actions">
  <div class="row">
    <div class="col-sm-2">
      <%= link_to t('actions.back'), admin_users_path, class: 'btn btn-info btn-sm' %>
    </div>
    <div class="col-sm-2">
      <%= link_to t('actions.edit'), edit_admin_user_path, class: 'btn btn-warning btn-sm' %>
    </div>
  </div>
</div>