config/routes.rb
################################################################################
#   12.02.2022  Adopted from Rails 6 (zt_admin)
################################################################################
Rails.application.routes.draw do
  # mount_devise_token_auth_for 'Account', at: 'auth'
 
  app_scope = MULTILINGUAL ? "/:locale" : "/"
  scope app_scope, locale: /#{I18n.available_locales.join("|")}/ do

    # Session resources
    get    'sessions/new'                                # sessions_new_path
    post   'login',  to: 'sessions#create'               # login_path  - creates new session (login)
    get  'logout', to: 'sessions#destroy', as: :logout # logout_path - destroys    session (log out)
  # delete 'logout', to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)

    namespace :admin do
      root 'panel#index'                                 # admin_root_path
      resources :users
      resources :samples
      resources :accounts, only: [:index, :show]
      # Add new admin resources before this line
    end
  
    namespace :api do
      namespace :v1 do
        resources :samples
      end
    end
    root 'pages#home' 
    get :demo, to: 'pages#demo', path: 'demo'
    resources :people
  end

  if MULTILINGUAL
    # Root route is directed to default locale
    root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

    # All other routes without locales are directed to the same ones with locales
    #get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false
  
    # Active Storage paths are excluded from the redirection process
    get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(rails\/active_storage|#{I18n.available_locales.join("|")})\/).*/}, format: false
  end
end

Rails.application.routes.draw do
  resources :people
  get 'pages/demo'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/admin/shared/_admin_top_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-faded">
  <div class="container-fluid">
    <!-- Brand (App Home Page) -->
    <div class="navbar-brand">
      <%= link_to image_tag('logos/dummy_logo.png', title: app_name,  size: '142x82'), root_path %>
    </div>
    <button aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-bs-target="#navbarNav" data-bs-toggle="collapse" type="button">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <div class="nav-link">
            <%= link_to  admin_root_path do %>
              <span aria-hidden="true" class="fas fa-tools fa-2x" style="color:navy"></span>
              <%= t(:admin_home) %>
            <% end %>
          </div>
        </li>
        <li class="nav-item">
          <% if @current_user.superadmin? %>
            <div class="nav-link">
              <%= link_to admin_users_path do %>
                <span aria-hidden="true" class="fas fa-users fa-2x" style="color:navy"></span>
                <%= t User.model_name.human(count: 2) %>
              <% end %>
            </div>
          <% else %>
            <div class="nav-link">
              <%= link_to edit_admin_user_path(@current_user) do %>
                <span aria-hidden="true" class="fas fa-user fa-2x" style="color:navy"></span>
                <%= t(:profile) %>
              <% end %>
            </div>
          <% end %>
        </li>

        <!-- Dropdown list -->
        <li class="nav-item dropdown">
          <a aria-expanded="false" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" id="navbarDropdown" role="button">
            <span aria-hidden="true" class="fas fa-database fa-2x" style="color:navy"></span>
            <%= t(:data) %>
          </a>
          <div aria-labelledby="navbarDropdown" class="dropdown-menu">
            <div class="dropdown-item" >
              <%= link_to t(Item.model_name.human(count: 2)),  admin_items_path %>
            </div>
            <div class="dropdown-item" >
              <%#= link_to t(Category.model_name.human(count: 2)),  admin_categories_path %>
            </div>
            <div class="dropdown-item">
              <%#= link_to t(Sample.model_name.human(count: 2)), admin_samples_path %>
            </div>
            <div class="dropdown-divider"></div>
            <div class="dropdown-item">
              <%= link_to t(:dummy), '#' %>
            </div>
          </div>
        </li>
      </ul>

      <ul class="navbar-nav">
        <% if MULTILINGUAL %>
          <li class="nav-item dropdown">
            <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" id="navbarDropdown" role="button">
              <span aria-hidden="true" class="fas fa-language fa-2x" style="color:navy"></span>
              <%= t(:language) %>
            </a>
            <%= language_switch_bootstrap('admin') %>
          </li>
        <% end %>
        <li class="nav-item">
          <div class="nav-link">
            <%= link_to(logout_path, method: 'delete') do %>
              <span aria-hidden="true" class="fas fa-sign-out-alt fa-2x" style="color:navy"></span>
              <%= t 'simple_form.submit.logout' %>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/admin/shared/_admin_top_navigation_sample.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-faded
  .container-fluid
    / Brand (App Home Page)
    .navbar-brand 
      = link_to image_tag('logos/dummy_logo.png', title: app_name,  size: '142x82'), root_path

    %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarNav", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarNav.collapse.navbar-collapse
      %ul.navbar-nav.me-auto
        %li.nav-item
          .nav-link
            = link_to  admin_root_path do
              %span.fas.fa-tools.fa-2x{"aria-hidden" => "true", "style" => "color:navy"}
              = t(:admin_home)
        %li.nav-item
          - if @current_user.superadmin?
            .nav-link
              = link_to admin_users_path do
                %span.fas.fa-users.fa-2x{"aria-hidden" => "true", "style" => "color:navy"}
                = t User.model_name.human(count: 2)
          - else
            .nav-link
              = link_to edit_admin_user_path(@current_user) do
                %span.fas.fa-user.fa-2x{"aria-hidden" => "true", "style" => "color:navy"}
                = t(:profile)

        / Dropdown list
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            %span.fas.fa-database.fa-2x{"aria-hidden" => "true", "style" =>  "color:navy"}
            = t(:data)
          .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            -# .dropdown-item
              = link_to t(Category.model_name.human(count: 2)),  admin_categories_path
            .dropdown-item
              = link_to t(Sample.model_name.human(count: 2)), admin_samples_path
            .dropdown-divider
            .dropdown-item
              = link_to t(:dummy), '#'

      %ul.navbar-nav
        - if MULTILINGUAL
          %li.nav-item.dropdown
            %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", :role => "button"}
              %span.fas.fa-language.fa-2x{"aria-hidden" => "true", "style" => "color:navy"}
              = t(:language)
            = language_switch_bootstrap('admin')

        %li.nav-item
          .nav-link
            = link_to(logout_path, method: 'delete') do
              %span.fas.fa-sign-out-alt.fa-2x{"aria-hidden" => "true", "style" => "color:navy"}
              = t 'simple_form.submit.logout'

app/views/admin/shared/_form_actions.html.erb
<hr/>
<div class="form_actions">
  <div class="row">
    <div class="col-sm-3">
      <%= f.submit t('actions.save'), class: 'btn btn-primary btn-sm' %>
    </div>
    <div class="col-sm-3">
      <%= link_to t('actions.back'), "admin_#{object.class.model_name.plural}".to_sym, class: 'btn btn-info btn-sm' %>
    </div>
  </div>
</div>

app/views/admin/shared/_form_ancestry.html.erb
<% entity = object.class.name.constantize %>
<% if entity.column_names.include? 'ancestry' %>
  <% if entity.respond_to? :active %>
    <% if entity.column_names.include? 'title' %>
      <%= f.input :ancestry, as: :select, collection: entity.active.map { |e| [e.title, e.id] } %>
    <% else %>
      <%= f.input :ancestry, as: :select, collection: entity.all#.active.map { |e| [e.name, e.id] } %>
    <% end %>
  <% else %>
    <%= f.input :ancestry, as: :select, collection: entity.all #.all.map { |e| [e.title, e.id] } %>
  <% end %>
<% end %>

app/views/admin/shared/_form_images.html.erb
<% entity = object.class.name.constantize %>
<% if entity.included_modules.include?(ImagesHandleable) %>
  <% if entity.reflect_on_attachment(:cover_image).present? %>
    <hr/>
    <div class="row">
      <div class="col-md-4">
        <%= f.label t 'images.cover_image' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <%= f.file_field :cover_image %>
      </div>
    </div>
    <br/>
    <div class="row">
      <% if object.cover_image.attached? %>
        <div class="col-md-2">
          <%= image_tag object.cover_image.variant(resize_to_fit: [100, 100]) %>
        </div>
        <div class="col-md-2">
          <%= f.check_box :remove_cover_image %>
          <i class="fas fa-trash"></i>
        </div>
      <% end %>
    </div>
  <% end %>
  <% if entity.reflect_on_attachment(:images).present? %>
    <hr/>
    <div class="row">
      <div class="col-md-4">
        <%= f.label t 'images.gallery' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <%= f.file_field :images, multiple: true %>
      </div>
    </div>
    <br/>
    <div class="row">
      <% if object.images.attached? %>
        <% object.images.each do |image| %>
          <div class="col-md-3 form-image-cell">
            <%= image_tag image.variant(resize_to_fit: [100, 100]) %>
            <%= check_box_tag 'image_to_remove_ids[]', image.id %>
            <i class="fas fa-trash"></i>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/admin/shared/_form_rich_text_content.html.erb
<% if object.class.name.constantize.reflect_on_association(:rich_text_content).present? %>
  <%= f.label t 'content' %>
  <div class="content-area">
    <%= f.rich_text_area :content %>
  </div>
<% end %>

app/views/admin/shared/_index_buttons.html.erb
<%= link_to t('actions.show'),   [:admin, resource],        class: 'btn btn-info btn-sm' %>
<%= link_to t('actions.edit'),   [:edit, :admin, resource], class: 'btn btn-warning btn-sm' %>
<%= link_to t('actions.delete'), [:admin, resource], data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-danger btn-sm' %>

<!-- ref: https://makandracards.com/makandra/1375-url_for-with-added-params not needed if *default_url_options* method is applied -->
<%#= link_to t('actions.show'),   polymorphic_url([:admin, resource],        locale: params[:locale]), class: 'btn btn-info btn-xs' %>
<%#= link_to t('actions.edit'),   polymorphic_url([:edit, :admin, resource], locale: params[:locale]), class: 'btn btn-warning btn-xs' %>
<%#= link_to t('actions.delete'), polymorphic_url([:admin, resource],        locale: params[:locale]), class: 'btn btn-danger  btn-xs', method: :delete, data: {confirm: t('messages.confirm')} %>

app/views/admin/shared/_show_action.html.erb
<br/>
<div class="row">
  <div class="col-md-2">
    <%= link_to t('actions.back'), "admin_#{object.class.model_name.plural}".to_sym, class: 'btn btn-info btn-sm' %>
  </div>
  <div class="col-md-2">
    <%= link_to t('actions.edit'), "edit_admin_#{object.class.model_name.singular}".to_sym, class: 'btn btn-warning btn-sm' %>
  </div>
</div>

app/views/admin/shared/_show_images.html.erb
<% entity = object.class.name.constantize %>
<% if entity.included_modules.include?(ImagesHandleable) %>
  <% if entity.reflect_on_attachment(:cover_image).present?  %>
    <table class="table table-striped">
      <tbody>
        <tr>
          <td>
            <%= t 'images.cover_image' %>
          </td>
          <td>
            <% if object.cover_image.attached? %>
              <%= image_tag object.cover_image.variant(resize_to_limit: [50, 50]) %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  <% end %>
  <% if object.images.attached? %>
    <table class="table table-striped">
      <tbody>
        <tr>
          <td>
            <%= t 'images.gallery' %>
          </td>
          <% object.images.each do |image| %>
            <td>
              <%= image_tag image.variant(resize_to_limit: [50, 50]) %>
            </td>
          <% end %>
        </tr>
      </tbody>
    </table>
  <% end %>
<% end %>

app/views/admin/shared/_show_rich_text_content.html.erb
<% if object.class.name.constantize.reflect_on_association(:rich_text_content).present? %>
  <%= t 'content' %>
  <div class="content-area">
    <%= object.content %>
  </div>
<% end %>

app/views/admin/shared/_status_buttons.html.erb
<p class="p-status">
  <%= "#{t('status.status')}:" %>
  &nbsp;&nbsp;
  <%= f.radio_button :status, :active, checked: true %>
  <%= label :status, t('status.active') %>
  &nbsp;
  <%= f.radio_button :status, :archived %>
  <%= label :status, t('status.archived') %>
</p>