config/routes.rb
################################################################################
#   12.02.2022  Adopted from Rails 6 (zt_admin)
################################################################################
Rails.application.routes.draw do
  # mount_devise_token_auth_for 'Account', at: 'auth'
 
  app_scope = MULTILINGUAL ? "/:locale" : "/"
  scope app_scope, locale: /#{I18n.available_locales.join("|")}/ do

    # Session resources
    get    'sessions/new'                                # sessions_new_path
    post   'login',  to: 'sessions#create'               # login_path  - creates new session (login)
    get  'logout', to: 'sessions#destroy', as: :logout # logout_path - destroys    session (log out)
  # delete 'logout', to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)

    namespace :admin do
      root 'panel#index'                                 # admin_root_path
      resources :users
      resources :samples
      resources :accounts, only: [:index, :show]
      # Add new admin resources before this line
    end
  
    namespace :api do
      namespace :v1 do
        resources :samples
      end
    end
    root 'pages#home' 
    get :demo, to: 'pages#demo', path: 'demo'
    resources :people
  end

  if MULTILINGUAL
    # Root route is directed to default locale
    root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

    # All other routes without locales are directed to the same ones with locales
    #get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false
  
    # Active Storage paths are excluded from the redirection process
    get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(rails\/active_storage|#{I18n.available_locales.join("|")})\/).*/}, format: false
  end
end

Rails.application.routes.draw do
  resources :people
  get 'pages/demo'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/sample.rb
###########################################################
# Model:  Sample
#
# Purpose:  Demo Entity
#
# Attributes
#   name        - string
#   title       - string
#   price       - decimal, default: 0.0
#   quantity    - integer, default: 0
#   content     - Active Text attachement
#   position    - sorting index:  integer, not NULL
#   status      - enum { active (0) | archived (1) }
#
#   cover_image - Active Storage attachement
#   images      - Active Storage attachements
#
#   05.11.2020  ZT
#   12.11.2020  Images handling shifted to Concerns
#   15.11.2020  Corrected
#   20.12.2020  Position added
###########################################################
class Sample < ApplicationRecord
  include Positionable
  include ImagesHandleable
  has_rich_text :content
  enum status:  %w(active archived)
  
  validates :name,     presence: true, uniqueness: true
  validates :title,    presence: true
  validates :price,    presence: true, numericality: {greater_than_or_equal_to: 0}
  validates :quantity, presence: true, numericality: {greater_than_or_equal_to: 0}
end

app/controllers/admin/samples_controller.rb
###########################################################
#   samples_controller.rb
#
#   Demo controller for Admin with Active Storage
#
#   05.11.2020  ZT
#   14.02.2022  Bug fixed
###########################################################
class Admin::SamplesController < Admin::BaseController
  before_action :set_sample,    only: [:show, :edit, :update,:destroy]
  after_action  :remove_images, only: :update

  def index
    @samples = policy_scope(Sample)
  end

  def show
    authorize @sample
  end

  def new
    @sample = Sample.new
    authorize @sample
  end

  def edit
    authorize @sample
  end

  def create
    @sample = Sample.new(sample_params)
    authorize @sample
    if @sample.save
      flash[:success] = t('messages.created', model: @sample.class.model_name.human)
      redirect_to [:admin, @sample]
    else      
      render :new
    end
  end

  def update
    authorize @sample
    if @sample.update(sample_params)
      flash[:success] = t('messages.updated', model: @sample.class.model_name.human)
      redirect_to [:admin, @sample]
    else      
      render :edit
    end
  end

  def destroy
    authorize @sample
    @sample.destroy
    flash[:success] = t('messages.deleted', model: @sample.class.model_name.human)
    redirect_to admin_samples_path
  end

  private
    # Uses callbacks to share common setup or constraints between actions
    def set_sample
      @sample = Sample.find(params[:id])
    end

    # Removes images, selected during Editing
    def remove_images
      @sample.cover_image.purge if sample_params[:remove_cover_image] == '1'
      image_to_remove_ids = params['image_to_remove_ids']
      if image_to_remove_ids.present?
        image_to_remove_ids.each do |image_to_remove_id|
          @sample.images.find(image_to_remove_id).purge
        end
      end
    end
  
    # Only allows a trusted parameter 'white list' through
    def sample_params
      params.require(:sample).permit(:name, :title, :sku, :price, :quantity, :description, :status, :content, :cover_image, :remove_cover_image, images: [])
    end
end

app/views/admin/samples/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-ms-6">
      <%= simple_form_for([:admin, @sample], html: {multipart: true}) do |f| %>
        <%= f.error_notification message: t('messages.error_notification') %>
        <div class="form-inputs">
          <%= f.input :name %>
          <%= f.input :title %>
          <%= f.input :price %>
          <%= f.input :quantity %>
          <%= f.input :status, default: 0 %>
          <%= render 'admin/shared/form_rich_text_content', f: f, object: @sample %>
          <%= render 'admin/shared/form_images', f: f, object: @sample %>
          <%= render 'admin/shared/form_actions', f: f, object: @sample %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/samples/edit.html.erb
<h1>
  <%= "#{t('actions.editing', model: @sample.class.model_name.human)}" %>
</h1>
<%= render 'form' %>

app/views/admin/samples/index.html.erb
<h1>
  <%= t Sample.model_name.human(count: 2) %>
</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th>
        <%= Sample.human_attribute_name(:position) %>
      </th>
      <th>
        <%= Sample.human_attribute_name(:name) %>
      </th>
      <th>
        <%= Sample.human_attribute_name(:title) %>
      </th>
      <th>
        <%= Sample.human_attribute_name(:price) %>
      </th>
      <th>
        <%= Sample.human_attribute_name(:quantity) %>
      </th>
      <th>
        <%= t 'status.status' %>
      </th>
      <th>
        <%= t "images.cover_image" %>
      </th>
      <th>
        <%= t 'actions.actions' %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @samples.each do |sample| %>
      <tr>
        <td>
          <%= sample.position %>
        </td>
        <td>
          <%= sample.name %>
        </td>
        <td>
          <%= sample.title %>
        </td>
        <td>
          <%= sample.price %>
        </td>
        <td>
          <%= sample.quantity %>
        </td>
        <td>
          <%= status_mark sample.status %>
        </td>
        <% if sample.cover_image.attached? %>
          <td>
            <%= image_tag sample.cover_image.variant(resize_to_fit: [50, 50]) %>
          </td>
        <% else %>
          <td></td>
        <% end %>
        <td>
          <%= render 'admin/shared/index_buttons', resource: sample %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>
<div class="row">
  <div class="col-md-2">
    <%= link_to t('actions.create'), new_admin_sample_path, class: 'btn btn-primary btn-sm' %>
  </div>
</div>

app/views/admin/samples/new.html.erb
<h1>
  <%= "#{t('actions.new', model: @sample.class.model_name.human)}" %>
</h1>
<%= render 'form' %>

app/views/admin/samples/show.html.erb
<div class="container">
  <h1>
    <%= t Sample.model_name.human %>
  </h1>
  <table class="table table-striped">
    <tbody>
      <% @sample.attributes.each do |key, value| %>
        <% if key == 'id' || key.include?('digest') || key == 'created_at' || key == 'updated_at' %>
          <!--/skip these attributes
          -->
        <% else %>
          <tr>
            <% if key == 'status' %>
              <td>
                <%= t 'status.status' %>
              </td>
              <td>
                <%= status_mark @sample.status %>
              </td>
            <% else %>
              <td>
                <%= t "activerecord.attributes.sample.#{key}" %>
              </td>
              <td>
                <%= value %>
              </td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
      <%= render 'admin/shared/show_images', object: @sample %>
    </tbody>
  </table>
  <%= render 'admin/shared/show_rich_text_content', object: @sample %>
  <%= render 'admin/shared/show_actions', object: @sample %>
</div>